# Generated by Django 4.2.13 on 2025-09-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
    ]
