# Generated by Django 4.2.13 on 2025-08-25 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_missing_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalApplicationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Soumise'), ('viewed', 'Consultée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('comment', 'Commentaire')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='users.professionalapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
