# Generated by Django 4.2.13 on 2025-08-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_professionalapplicationaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalapplication',
            name='salon_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
