# Generated by Django 4.2.13 on 2025-08-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfileExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('social_instagram', models.CharField(blank=True, max_length=255)),
                ('social_facebook', models.CharField(blank=True, max_length=255)),
                ('social_tiktok', models.CharField(blank=True, max_length=255)),
                ('services', models.JSONField(default=list, help_text="Liste d'objets {name, duration_min, price}")),
                ('working_days', models.JSONField(default=list, help_text='Jours de travail')),
                ('working_hours', models.JSONField(default=dict, help_text="Ex: {start:'09:00', end:'18:00'}")),
                ('gallery', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='users.professional')),
            ],
        ),
    ]
