# Generated by Django 4.2.13 on 2025-09-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_client_address_client_city_client_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofileextra',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='price',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='primary_service',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/'),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='spoken_languages',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
