# Generated by Django 4.2.13 on 2025-10-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_professionalprofileextra_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalapplication',
            name='governorate',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='governorate',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
