# Generated by Django 4.2.13 on 2025-12-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_professionalapplication_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalapplication',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='Liste des services proposés'),
        ),
    ]
