# Generated by Django 4.2.13 on 2025-12-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_services_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='professionalapplication',
            name='activity_category',
            field=models.CharField(choices=[('hairdressing', 'Coiffure'), ('haircut_women', 'Coupe femme'), ('haircut_men', 'Coupe homme'), ('haircut_children', 'Coupe enfant'), ('hair_coloring', 'Coloration'), ('highlights', 'Mèches & Balayage'), ('hair_styling', 'Brushing & Coiffage'), ('hair_treatment', 'Soins capillaires'), ('keratin', 'Lissage & Kératine'), ('hair_extensions', 'Extensions cheveux'), ('braiding', 'Tresses & Nattes'), ('bridal_hair', 'Coiffure mariée'), ('makeup', 'Maquillage'), ('bridal_makeup', 'Maquillage mariée'), ('evening_makeup', 'Maquillage soirée'), ('natural_makeup', 'Maquillage naturel'), ('makeup_lesson', 'Cours de maquillage'), ('manicure', 'Manucure'), ('pedicure', 'Pédicure'), ('nail_art', 'Nail art'), ('gel_nails', 'Pose gel'), ('acrylic_nails', 'Pose résine'), ('semi_permanent', 'Semi-permanent'), ('nail_care', 'Soins des ongles'), ('esthetics', 'Esthétique'), ('facial', 'Soin du visage'), ('deep_cleansing', 'Nettoyage de peau'), ('anti_aging', 'Soin anti-âge'), ('hydration', 'Soin hydratant'), ('acne_treatment', 'Traitement acné'), ('microdermabrasion', 'Microdermabrasion'), ('chemical_peel', 'Peeling'), ('led_therapy', 'Luminothérapie LED'), ('waxing', 'Épilation cire'), ('waxing_face', 'Épilation visage'), ('waxing_body', 'Épilation corps'), ('waxing_bikini', 'Épilation maillot'), ('threading', 'Épilation au fil'), ('laser_hair', 'Épilation laser'), ('sugaring', 'Épilation au sucre'), ('eyebrows', 'Épilation sourcils'), ('eyebrow_tint', 'Teinture sourcils'), ('eyebrow_lamination', 'Brow lamination'), ('microblading', 'Microblading'), ('eyelash_extensions', 'Extension de cils'), ('eyelash_lift', 'Rehaussement de cils'), ('eyelash_tint', 'Teinture de cils'), ('massage', 'Massage'), ('relaxing_massage', 'Massage relaxant'), ('deep_tissue', 'Massage deep tissue'), ('hot_stone', 'Massage pierres chaudes'), ('aromatherapy', 'Aromathérapie'), ('reflexology', 'Réflexologie'), ('lymphatic_drainage', 'Drainage lymphatique'), ('prenatal_massage', 'Massage prénatal'), ('body_treatment', 'Soin du corps'), ('body_scrub', 'Gommage corps'), ('body_wrap', 'Enveloppement'), ('slimming', 'Soin minceur'), ('cellulite', 'Traitement cellulite'), ('tanning', 'Bronzage'), ('spray_tan', 'Autobronzant'), ('spa', 'Spa'), ('hammam', 'Hammam'), ('sauna', 'Sauna'), ('jacuzzi', 'Jacuzzi'), ('permanent_makeup', 'Maquillage permanent'), ('lip_tattoo', 'Tatouage lèvres'), ('eyeliner_tattoo', 'Tatouage eye-liner'), ('barber', 'Barbier'), ('beard_trim', 'Taille de barbe'), ('beard_care', 'Soins barbe'), ('men_facial', 'Soin visage homme'), ('henna', 'Henné'), ('teeth_whitening', 'Blanchiment dentaire'), ('piercing', 'Piercing'), ('other', 'Autre')], max_length=32),
        ),
    ]
