# Generated by Django 4.2.13 on 2025-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_gender_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofileextra',
            name='email',
            field=models.EmailField(blank=True, help_text='Email principal du professionnel', max_length=254),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='email_secondary',
            field=models.EmailField(blank=True, help_text='Email secondaire', max_length=254),
        ),
        migrations.AddField(
            model_name='professionalprofileextra',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Téléphone secondaire', max_length=32),
        ),
        migrations.AlterField(
            model_name='professionalapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='professionalprofileextra',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], default='female', max_length=10),
        ),
    ]
